steps:
  # Build the containes
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/deploykey:$COMMIT_SHA', '-t', 'gcr.io/$PROJECT_ID/deploykey:latest', './deploykey']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/npm-ssh:$COMMIT_SHA', '-t', 'gcr.io/$PROJECT_ID/npm-ssh:current', './npm-ssh']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/npm-deploykey:$COMMIT_SHA', '-t', 'gcr.io/$PROJECT_ID/npm-deploykey:current', './npm-deploykey']
  
  # Test the deploykey + npm-ssh
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/deploykey-testkey:$COMMIT_SHA', '-t', 'gcr.io/$PROJECT_ID/deploykey-testkey:latest', './examples/deploykey-testkey']
  - name: 'gcr.io/$PROJECT_ID/deploykey-testkey:latest'
    dir: './examples/hello-world'
    env: ['KMS_KEY_NAME=$PROJECT_ID/global/cloudbuilder/github-deploykey']
    volumes:
      - name: 'deploykey'
        path: /root/.ssh
  - name: 'gcr.io/$PROJECT_ID/npm-ssh:current'
    args: ['install']
    dir: './examples/hello-world'
    volumes:
      - name: 'deploykey'
        path: /root/.ssh
  - name: 'gcr.io/$PROJECT_ID/npm-ssh:current'
    args: ['test']
    dir: './examples/hello-world'

  # Clean up
  - name: 'ubuntu'
    args: ['rm', '-rf', 'node_modules']
    dir: './examples/hello-world'

  # Test the npm-deploykey
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/npm-deploykey-testkey:$COMMIT_SHA', '-t', 'gcr.io/$PROJECT_ID/npm-deploykey-testkey:latest', './examples/npm-deploykey-testkey']
  - name: 'gcr.io/$PROJECT_ID/npm-deploykey-testkey:current'
    secretEnv: ['SSH_KEY_PASSWORD']
    args: ['install']
    dir: './examples/hello-world'
  - name: 'gcr.io/$PROJECT_ID/npm-ssh:current'
    args: ['test']
    dir: './examples/hello-world'
  
images: 
- 'gcr.io/$PROJECT_ID/deploykey:$COMMIT_SHA'
- 'gcr.io/$PROJECT_ID/deploykey:latest'
- 'gcr.io/$PROJECT_ID/npm-ssh:$COMMIT_SHA'
- 'gcr.io/$PROJECT_ID/npm-ssh:current'
- 'gcr.io/$PROJECT_ID/npm-deploykey:$COMMIT_SHA'
- 'gcr.io/$PROJECT_ID/npm-deploykey:current'

secrets:
- kmsKeyName: projects/connectedcars-staging/locations/global/keyRings/cloudbuilder/cryptoKeys/github-deploykey
  secretEnv:
    SSH_KEY_PASSWORD: CiQAiXqwBmhqi+Od146HAG9E3cNiaCEzqkBl6X9hTatGe8B6b3kSUgCbUdOQElBUoff8hJBS5ouLnn93D26YGUvZT6Hcxcx+5JtO6FgYhoWg4aMFIGu98E1qcRUMTeoybPD4NyIG6MEL1kf8/qrtE0652YUiVjVAZ1c=